# Project: Diploma_jsontocsv (code)
# File: webapp/app.py

import base64
import json
import os
import subprocess
import sys
from hashlib import sha256
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Any, Optional

import pandas as pd
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles

ROOT = Path(__file__).resolve().parents[1]  # Diploma_jsontocsv/
PIPELINE = ROOT / "pipeline_lmstudio_pdf.py"
OUT_DIR = ROOT / "out"
RAG_INDEX_PATH = OUT_DIR / "rag_index.jsonl"
STRUCTURE_EXAMPLES_DIR = OUT_DIR / "structure_examples"

# Dataset paths (generated by ndjson_to_enriched_datasets.py)
DATASETS_DIR = ROOT / "datasets_enriched"
DATASET_MAP = {
    "5to10": DATASETS_DIR / "beauty_5to10_enriched.csv",
    "8to10": DATASETS_DIR / "beauty_8to10_enriched.csv",
}

PROFILE_PRESETS: Dict[str, Dict[str, int]] = {
    "fast": {
        "reviews_max_chars": 1600,
        "structure_example_max_chars": 1000,
        "revision_strategy_max_chars": 2800,
        "revision_judge_max_chars": 1000,
        "gen_max_tokens": 700,
        "judge_max_tokens": 500,
    },
    "balanced": {
        "reviews_max_chars": 2400,
        "structure_example_max_chars": 1800,
        "revision_strategy_max_chars": 4500,
        "revision_judge_max_chars": 1800,
        "gen_max_tokens": 1000,
        "judge_max_tokens": 900,
    },
    "quality": {
        "reviews_max_chars": 3200,
        "structure_example_max_chars": 2400,
        "revision_strategy_max_chars": 6500,
        "revision_judge_max_chars": 2600,
        "gen_max_tokens": 1400,
        "judge_max_tokens": 1200,
    },
}

app = FastAPI(title="Diploma Strategy Generator")

STATIC_DIR = Path(__file__).parent / "static"
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

OUT_DIR.mkdir(parents=True, exist_ok=True)
app.mount("/out", StaticFiles(directory=str(OUT_DIR)), name="out")


@app.get("/", response_class=HTMLResponse)
def index():
    html_path = STATIC_DIR / "index.html"
    return html_path.read_text(encoding="utf-8")


def _load_df(dataset_key: str) -> pd.DataFrame:
    if dataset_key not in DATASET_MAP:
        raise ValueError(f"Unknown dataset: {dataset_key}")

    csv_path = DATASET_MAP[dataset_key]
    if not csv_path.exists():
        raise FileNotFoundError(f"Dataset CSV not found: {csv_path}")

    df = pd.read_csv(csv_path, dtype=str, keep_default_na=False)

    # ensure columns
    if "category_lv2" not in df.columns:
        df["category_lv2"] = "Other/Unclear"
    if "product_brand" not in df.columns:
        df["product_brand"] = ""
    if "review_count" not in df.columns:
        df["review_count"] = df.groupby("asin")["asin"].transform("size")

    # types
    try:
        df["review_count"] = df["review_count"].astype(int)
    except Exception:
        df["review_count"] = pd.to_numeric(df["review_count"], errors="coerce").fillna(0).astype(int)

    return df


def _normalize_target_score(value: float) -> str:
    return f"{float(value):.2f}"


def _normalize_structure_example(content: str) -> str:
    return content.strip()


def _structure_example_hash(content: str) -> str:
    normalized = _normalize_structure_example(content)
    if not normalized:
        return ""
    return sha256(normalized.encode("utf-8")).hexdigest()


def _bytes_hash(data: bytes) -> str:
    return sha256(data).hexdigest() if data else ""


def _read_rag_index() -> List[Dict[str, Any]]:
    if not RAG_INDEX_PATH.exists():
        return []

    rows: List[Dict[str, Any]] = []
    with RAG_INDEX_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(item, dict):
                rows.append(item)
    return rows


def _store_structure_example(content: str, filename: str = "") -> Path:
    normalized = _normalize_structure_example(content)
    digest = _structure_example_hash(normalized)
    if not digest:
        raise ValueError("Structure example content is empty.")

    suffix = Path(filename).suffix if filename else ".txt"
    if not suffix:
        suffix = ".txt"

    STRUCTURE_EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)
    path = STRUCTURE_EXAMPLES_DIR / f"{digest}{suffix}"
    path.write_text(normalized, encoding="utf-8")
    return path


def _store_structure_example_bytes(data: bytes, filename: str = "") -> Path:
    digest = _bytes_hash(data)
    if not digest:
        raise ValueError("Structure example file is empty.")

    suffix = Path(filename).suffix if filename else ".bin"
    if not suffix:
        suffix = ".bin"

    STRUCTURE_EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)
    path = STRUCTURE_EXAMPLES_DIR / f"{digest}{suffix}"
    path.write_bytes(data)
    return path


def _find_rag_match(asin: str, target_score: float, structure_example_hash: str) -> Optional[Dict[str, Any]]:
    target_norm = _normalize_target_score(target_score)

    for item in reversed(_read_rag_index()):
        if item.get("asin") != asin:
            continue
        if item.get("target_score") != target_norm:
            continue
        if item.get("structure_example_hash", "") != structure_example_hash:
            continue

        strategy_path = OUT_DIR / str(item.get("strategy_json_file", ""))
        judge_path = OUT_DIR / str(item.get("judge_json_file", ""))
        pdf_path = OUT_DIR / str(item.get("pdf_file", ""))

        if strategy_path.exists() and judge_path.exists() and pdf_path.exists():
            return item

    return None


def _append_rag_entry(entry: Dict[str, Any]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with RAG_INDEX_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


def _inspect_structure_example_path(path: Path) -> Dict[str, Any]:
    cmd = [sys.executable, "-c", "\n".join([
        "import json, sys",
        "from pipeline_lmstudio_pdf import inspect_structure_example",
        "result = inspect_structure_example(sys.argv[1])",
        "print(json.dumps(result, ensure_ascii=False))",
    ]), str(path)]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=str(ROOT), timeout=60)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or proc.stdout.strip() or "Failed to inspect structure example.")
    return json.loads(proc.stdout.strip() or "{}")


@app.get("/api/categories")
def api_categories(dataset: str = Query("8to10")):
    try:
        df = _load_df(dataset)
        cats = (
            df.groupby("category_lv2")["asin"].nunique()
            .reset_index(name="num_products")
            .sort_values("category_lv2")
            .to_dict(orient="records")
        )
        return {"ok": True, "categories": cats}
    except Exception as e:
        return {"ok": False, "error": repr(e)}


@app.get("/api/products")
def api_products(
    dataset: str = Query("8to10"),
    category: str = Query("", description="Optional category_lv2 filter"),
):
    try:
        df = _load_df(dataset)

        if category:
            df = df[df["category_lv2"] == category].copy()

        products = (
            df[["asin", "product_title", "product_brand", "category_lv2", "review_count"]]
            .drop_duplicates(subset=["asin"])
            .copy()
        )

        products["max_k"] = products["review_count"].clip(upper=10)
        products = products.sort_values(["category_lv2", "product_title"]).to_dict(orient="records")

        return {"ok": True, "products": products}
    except Exception as e:
        return {"ok": False, "error": repr(e)}


@app.post("/api/generate")
async def api_generate(request: Request):
    try:
        payload = await request.json()
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid JSON body: {e!r}")

    dataset = str(payload.get("dataset", "8to10"))
    asin = str(payload.get("asin", "")).strip()
    host = str(payload.get("host", "http://localhost:1234")).strip()
    model = str(payload.get("model", "")).strip()
    judge_model = str(payload.get("judge_model", "gpt-4.1-mini")).strip()
    k = int(payload.get("k", 8))
    target_score = float(payload.get("target_score", 9.0))
    max_rounds = int(payload.get("max_rounds", 4))
    request_timeout_sec = int(payload.get("request_timeout_sec", 60 * 30))
    profile = str(payload.get("profile", "balanced")).strip().lower() or "balanced"
    structure_example_content = str(payload.get("structure_example_content", "") or "")
    structure_example_name = str(payload.get("structure_example_name", "") or "")
    structure_example_base64 = str(payload.get("structure_example_base64", "") or "")

    if dataset not in DATASET_MAP:
        return {"ok": False, "error": f"Unknown dataset: {dataset}"}
    if not asin:
        return {"ok": False, "error": "ASIN is required."}
    if not model:
        return {"ok": False, "error": "Model is required."}
    if profile not in PROFILE_PRESETS:
        return {"ok": False, "error": f"Unknown profile: {profile}"}

    csv_path = DATASET_MAP[dataset]
    if not csv_path.exists():
        return {"ok": False, "error": f"Dataset CSV not found: {csv_path}"}

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    STRUCTURE_EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)

    structure_hash = _structure_example_hash(structure_example_content)
    structure_example_path: Optional[Path] = None
    if structure_example_base64:
        try:
            structure_bytes = base64.b64decode(structure_example_base64)
        except Exception as e:
            return {"ok": False, "error": f"Invalid base64 structure example: {e!r}"}
        structure_hash = _bytes_hash(structure_bytes)
        if structure_hash:
            structure_example_path = _store_structure_example_bytes(structure_bytes, structure_example_name)
    elif structure_hash:
        structure_example_path = _store_structure_example(structure_example_content, structure_example_name)

    rag_match = _find_rag_match(
        asin=asin,
        target_score=target_score,
        structure_example_hash=structure_hash,
    )
    if rag_match is not None:
        return {
            "ok": True,
            "asin": asin,
            "pdf_url": f"/out/{rag_match['pdf_file']}",
            "strategy_json_url": f"/out/{rag_match['strategy_json_file']}",
            "judge_json_url": f"/out/{rag_match['judge_json_file']}",
            "stdout_tail": "Returned from RAG cache.",
            "source": "rag",
            "cached": True,
            "cached_target_score": rag_match["target_score"],
            "structure_example_hash": structure_hash,
            "profile": profile,
        }

    if not os.environ.get("OPENAI_API_KEY"):
        return {"ok": False, "error": "OPENAI_API_KEY is not set in environment."}

    cmd = [
        sys.executable,
        str(PIPELINE),
        "--csv", str(csv_path),
        "--out-dir", str(OUT_DIR),
        "--host", host,
        "--model", model,
        "--judge-provider", "openai",
        "--judge-model", judge_model,
        "--openai-api-key", os.environ.get("OPENAI_API_KEY", ""),
        "--asin", asin,
        "--k", str(k),
        "--target-score", str(target_score),
        "--max-rounds", str(max_rounds),
        "--max-products", "1",
    ]
    for arg_name, arg_value in PROFILE_PRESETS[profile].items():
        cmd.extend([f"--{arg_name.replace('_', '-')}", str(arg_value)])
    if structure_example_path is not None:
        cmd.extend(["--structure-example-file", str(structure_example_path)])

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=str(ROOT),
            timeout=max(60, request_timeout_sec),
        )
    except subprocess.TimeoutExpired as e:
        return {
            "ok": False,
            "error": (
                f"Pipeline timed out after {max(60, request_timeout_sec)} seconds. "
                "Try reducing K/max rounds, using a smaller template file, or increasing request_timeout_sec."
            ),
            "stdout": (e.stdout or "")[-6000:],
            "stderr": (e.stderr or "")[-6000:],
        }
    except Exception as e:
        return {"ok": False, "error": repr(e)}

    if proc.returncode != 0:
        return {
            "ok": False,
            "error": "Pipeline failed",
            "stdout": proc.stdout[-6000:],
            "stderr": proc.stderr[-6000:],
        }

    pdf_name = f"{asin}_final_strategy.pdf"
    json_name = f"{asin}_final_strategy.json"
    judge_name = f"{asin}_final_judge.json"

    judge_score = ""
    judge_path = OUT_DIR / judge_name
    if judge_path.exists():
        try:
            judge_data = json.loads(judge_path.read_text(encoding="utf-8"))
            judge_score = judge_data.get("score", "")
        except Exception:
            judge_score = ""

    _append_rag_entry({
        "asin": asin,
        "dataset": dataset,
        "target_score": _normalize_target_score(target_score),
        "structure_example_hash": structure_hash,
        "k": int(k),
        "generator_model": model,
        "judge_model": judge_model,
        "judge_score": judge_score,
        "strategy_json_file": json_name,
        "judge_json_file": judge_name,
        "pdf_file": pdf_name,
        "created_at": datetime.now(timezone.utc).isoformat(),
    })

    return {
        "ok": True,
        "asin": asin,
        "pdf_url": f"/out/{pdf_name}",
        "strategy_json_url": f"/out/{json_name}",
        "judge_json_url": f"/out/{judge_name}",
        "stdout_tail": proc.stdout[-4000:],
        "source": "pipeline",
        "cached": False,
        "structure_example_hash": structure_hash,
        "profile": profile,
    }


@app.post("/api/inspect-template")
async def api_inspect_template(request: Request):
    try:
        payload = await request.json()
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid JSON body: {e!r}")

    structure_example_content = str(payload.get("structure_example_content", "") or "")
    structure_example_name = str(payload.get("structure_example_name", "") or "")
    structure_example_base64 = str(payload.get("structure_example_base64", "") or "")

    if not structure_example_content and not structure_example_base64:
        return {"ok": False, "error": "No template file provided."}

    STRUCTURE_EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)

    try:
        if structure_example_base64:
            structure_bytes = base64.b64decode(structure_example_base64)
            structure_path = _store_structure_example_bytes(structure_bytes, structure_example_name)
        else:
            structure_path = _store_structure_example(structure_example_content, structure_example_name)

        info = _inspect_structure_example_path(structure_path)
        if not info.get("ok"):
            return {
                "ok": False,
                "error": "Could not extract usable text from this template file.",
                "chars": info.get("chars", 0),
                "preview": info.get("preview", ""),
            }

        return {
            "ok": True,
            "chars": info.get("chars", 0),
            "preview": info.get("preview", ""),
            "hash": info.get("hash", ""),
        }
    except Exception as e:
        return {"ok": False, "error": repr(e)}
